---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: front-end
          image: bharathsharath/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend-svc
spec:
  selector:
    app: react-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31110
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back-end
          image: bharathsharath/backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8081


---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: back
spec:
  selector:
    app: back
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31111
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-cont
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017


---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 31112
  type: NodePort

